# Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Files

In [2]:
csv_data = "spain_temperatures.csv"

In [3]:
df = pd.read_csv(csv_data)

In [4]:
df

,Unnamed: 0,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,horatmin,...,horatmax,dir,velmedia,racha,horaracha,sol,presMax,horaPresMax,presMin,horaPresMin
0,0,2016-12-01,1111,SANTANDER,CANTABRIA,52,"15,0","0,0","12,2",23:20,...,12:55,19.0,"3,3","10,6",03:08,"8,3","1018,5",00,"1014,3",24
1,1,2016-12-02,1111,SANTANDER,CANTABRIA,52,"12,6","0,0","9,5",23:59,...,12:30,20.0,"2,2","5,3",07:15,"8,5","1014,3",00,"1008,3",24
2,2,2016-12-03,1111,SANTANDER,CANTABRIA,52,"12,8","0,0","9,0",05:05,...,14:05,21.0,"1,9","7,8",21:03,"7,9","1008,3",00,"1001,0",18
3,3,2016-12-04,1111,SANTANDER,CANTABRIA,52,"14,9","0,0","11,0",00:40,...,12:20,19.0,"5,6","12,5",03:50,"2,4","1006,8",24,"1000,6",Varias
4,4,2016-12-05,1111,SANTANDER,CANTABRIA,52,"18,1","0,0","15,0",07:55,...,13:15,18.0,"2,8","10,0",01:38,"4,8","1015,7",24,"1006,8",00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26892,26892,2021-10-28,2422,VALLADOLID,VALLADOLID,735,"11,5","0,6","3,0",07:20,...,14:30,22.0,"1,4","8,6",14:10,"8,4","934,2",00,"927,8",24
26893,26893,2021-10-29,2422,VALLADOLID,VALLADOLID,735,"12,8","11,6","10,4",08:50,...,11:50,26.0,"2,5","9,2",13:20,"0,0","927,8",00,"917,0",24
26894,26894,2021-10-30,2422,VALLADOLID,VALLADOLID,735,"13,8","5,4","11,7",00:00,...,12:30,27.0,"2,8","11,1",06:20,"0,3","926,9",23,"916,6",03
26895,26895,2021-10-31,2422,VALLADOLID,VALLADOLID,735,"15,0","8,4","11,3",23:59,...,14:50,25.0,"3,6","13,1",14:40,"0,4","927,9",22,"924,6",04
26896,26896,2021-11-01,2422,VALLADOLID,VALLADOLID,735,"10,8","0,0","7,4",23:40,...,14:20,24.0,"1,9","10,6",16:20,"7,9","931,2",22,"926,5",02

In [5]:
#Keeping only relevant columns and changing fecha to datetime
df=(df
 .drop(columns=[
     "Unnamed: 0","indicativo", "altitud", "dir", "presMax", "horaPresMax", "presMin", "horaPresMin"])
 .replace(",",".", regex=True)
 .assign(fecha = pd.to_datetime(df["fecha"])
#         ,tmed = pd.to_numeric(df["tmed"])
        )
#        horatmin = pd.to_datetime(df["horatmin"], format="%H:%M", errors="raise"))
# .to_datetime(df["fecha"])
# [df["nombre"]!="BARCELONA, FABRA"]
)

In [6]:
df

,fecha,nombre,provincia,tmed,prec,tmin,horatmin,tmax,horatmax,velmedia,racha,horaracha,sol
0,2016-12-01,SANTANDER,CANTABRIA,15.0,0.0,12.2,23:20,17.8,12:55,3.3,10.6,03:08,8.3
1,2016-12-02,SANTANDER,CANTABRIA,12.6,0.0,9.5,23:59,15.6,12:30,2.2,5.3,07:15,8.5
2,2016-12-03,SANTANDER,CANTABRIA,12.8,0.0,9.0,05:05,16.6,14:05,1.9,7.8,21:03,7.9
3,2016-12-04,SANTANDER,CANTABRIA,14.9,0.0,11.0,00:40,18.8,12:20,5.6,12.5,03:50,2.4
4,2016-12-05,SANTANDER,CANTABRIA,18.1,0.0,15.0,07:55,21.2,13:15,2.8,10.0,01:38,4.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26892,2021-10-28,VALLADOLID,VALLADOLID,11.5,0.6,3.0,07:20,20.0,14:30,1.4,8.6,14:10,8.4
26893,2021-10-29,VALLADOLID,VALLADOLID,12.8,11.6,10.4,08:50,15.1,11:50,2.5,9.2,13:20,0.0
26894,2021-10-30,VALLADOLID,VALLADOLID,13.8,5.4,11.7,00:00,16.0,12:30,2.8,11.1,06:20,0.3
26895,2021-10-31,VALLADOLID,VALLADOLID,15.0,8.4,11.3,23:59,18.7,14:50,3.6,13.1,14:40,0.4
26896,2021-11-01,VALLADOLID,VALLADOLID,10.8,0.0,7.4,23:40,14.3,14:20,1.9,10.6,16:20,7.9

In [7]:
df["nombre"].value_counts()

SANTANDER                          1797
BILBAO AEROPUERTO                  1797
DONOSTIA/SAN SEBASTIÁN. IGUELDO    1797
OVIEDO                             1797
A CORUÑA                           1797
BARCELONA                          1797
VALÈNCIA                           1797
MURCIA                             1797
SEVILLA AEROPUERTO                 1797
MADRID. CUATRO VIENTOS             1797
VALLADOLID                         1797
ZARAGOZA. VALDESPARTERA            1795
SALAMANCA                          1793
MÁLAGA. CENTRO METEOROLÓGICO       1777
BARCELONA. FABRA                   1765
Name: nombre, dtype: int64

# Santander

## Notes

In [8]:
#df[(df["nombre"]=='SANTANDER')].groupby(df["fecha"].dt.year).count()["fecha"].values
#years = np.arange(2016,2022,1)
#dict = {}
#for index in range(0,len(years)):
#    dict[years[index]]=(df[(df["nombre"]=='SANTANDER')].groupby(df["fecha"].dt.year).count()["fecha"].values)[index]


#

    -1797 rows
    -Min date: 2016-12-01
    -Max date: 2021-11-01
    -Rows per year:
        -2016: 31, 2017: 365, 2018: 365, 2019: 365, 2020: 366, 2021: 305
    -Null values:
        -2017-01-06 for Sol
        -2020-08-22 for horatmin
        -2018-05-07	& 2021-09-10 for horaracha
    -'Varias' values contained in following columns:
        -horatmin
        -horatmax
        -horaracha

## General df

In [9]:
((df[df["nombre"]=="SANTANDER"]
 .dropna()
.assign(tmed = pd.to_numeric(df["tmed"])
       ,prec = pd.to_numeric(df["prec"], errors="coerce").fillna(0)
        ,tmin = pd.to_numeric(df["tmin"])
        ,tmax = pd.to_numeric(df["tmax"])
        ,velmedia = pd.to_numeric(df["velmedia"])
        ,racha = pd.to_numeric(df["racha"])
        ,sol = pd.to_numeric(df["sol"])
       )
  .astype({"nombre": "string", "provincia": "string"})
  .drop(columns=["horatmin","horatmax","horaracha"])
#  .query("horatmin=='Varias'")
)
)#.info()
#["fecha"].dt.year.value_counts()

,fecha,nombre,provincia,tmed,prec,tmin,tmax,velmedia,racha,sol
0,2016-12-01,SANTANDER,CANTABRIA,15.0,0.0,12.2,17.8,3.3,10.6,8.3
1,2016-12-02,SANTANDER,CANTABRIA,12.6,0.0,9.5,15.6,2.2,5.3,8.5
2,2016-12-03,SANTANDER,CANTABRIA,12.8,0.0,9.0,16.6,1.9,7.8,7.9
3,2016-12-04,SANTANDER,CANTABRIA,14.9,0.0,11.0,18.8,5.6,12.5,2.4
4,2016-12-05,SANTANDER,CANTABRIA,18.1,0.0,15.0,21.2,2.8,10.0,4.8
...,...,...,...,...,...,...,...,...,...,...
1792,2021-10-28,SANTANDER,CANTABRIA,17.4,0.0,13.2,21.5,3.9,11.4,7.7
1793,2021-10-29,SANTANDER,CANTABRIA,16.8,5.5,14.5,19.2,2.8,13.3,0.0
1794,2021-10-30,SANTANDER,CANTABRIA,17.0,0.1,14.5,19.4,3.3,11.7,0.1
1795,2021-10-31,SANTANDER,CANTABRIA,17.9,10.1,13.0,22.8,5.6,15.3,1.2
1796,2021-11-01,SANTANDER,CANTABRIA,14.4,0.0,12.0,16.8,6.4,16.1,8.6

## Min_max

In [ ]:
(
((df[(df["nombre"]=="SANTANDER")&(df["horatmin"]!='Varias')]
  .dropna()
#  .query("horatmin!='Varias' & horatmax!='Varias' & horaracha!='Varias'")
  .assign(tmed = pd.to_numeric(df["tmed"])
       ,prec = pd.to_numeric(df["prec"], errors="coerce").fillna(0)
        ,tmin = pd.to_numeric(df["tmin"])
        ,tmax = pd.to_numeric(df["tmax"])
        ,velmedia = pd.to_numeric(df["velmedia"])
        ,racha = pd.to_numeric(df["racha"])
        ,sol = pd.to_numeric(df["sol"])
#        ,horatmin = pd.to_datetime(df["fecha"].astype(str)+" "+df["horatmin"].astype(str))
#        ,horatmax = df["fecha"].astype(str)+" "+df["horatmax"].astype(str)
#        ,horaracha = df["fecha"].astype(str)+" "+df["horaracha"].astype(str)
       )
)
)
["horatmin"]
).value_counts()